# Generated by Django 2.1.1 on 2018-09-28 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port_Proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='port_Proj.Posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='port_Proj.Users'),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='page',
        ),
        migrations.AddField(
            model_name='posts',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='port_Proj.Users'),
        ),
    ]
